# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_0.xci
# IP: The module: 'jesd204_rx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_rx_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_0.xci
# IP: The module: 'jesd204_rx_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
