# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0.xci
# IP: The module: 'mb_subsystem_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2 || ORIG_REF_NAME==bd_1ed2} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_eth_buf_0 || ORIG_REF_NAME==bd_1ed2_eth_buf_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/bd_1ed2_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_2/bd_1ed2_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1ed2_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_3/bd_1ed2_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1ed2_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_4/bd_1ed2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_xlconstant_0_0 || ORIG_REF_NAME==bd_1ed2_xlconstant_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_5/bd_1ed2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1ed2_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2_ooc.xdc

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/synth/mb_subsystem_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0.xci
# IP: The module: 'mb_subsystem_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2 || ORIG_REF_NAME==bd_1ed2} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_eth_buf_0 || ORIG_REF_NAME==bd_1ed2_eth_buf_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/bd_1ed2_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_mac_0 || ORIG_REF_NAME==bd_1ed2_mac_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_2/bd_1ed2_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1ed2_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_3/bd_1ed2_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1ed2_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_4/bd_1ed2_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_xlconstant_0_0 || ORIG_REF_NAME==bd_1ed2_xlconstant_0_0} -quiet] -quiet

# IP: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_5/bd_1ed2_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1ed2_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1ed2_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2_ooc.xdc

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/synth/mb_subsystem_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
