# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Genesys2.xdc

# IP: ip/jesd204_rx_static_config_0/jesd204_rx_static_config_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_rx_static_config_0 || ORIG_REF_NAME==jesd204_rx_static_config_0} -quiet] -quiet

# IP: ip/jesd204_phy_0_2/jesd204_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_phy_0 || ORIG_REF_NAME==jesd204_phy_0} -quiet] -quiet

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_xlconcat_0/mb_subsystem_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_subsystem_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_timer_0_0 || ORIG_REF_NAME==mb_subsystem_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_refclk_0/mb_subsystem_axi_ethernet_0_refclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_ethernet_0_refclk_0 || ORIG_REF_NAME==mb_subsystem_axi_ethernet_0_refclk_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/mb_subsystem_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_smc_0 || ORIG_REF_NAME==mb_subsystem_axi_smc_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_0 || ORIG_REF_NAME==mb_subsystem_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_0_1/mb_subsystem_axi_quad_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_subsystem_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/mb_subsystem_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_1_0/mb_subsystem_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_quad_spi_1_0 || ORIG_REF_NAME==mb_subsystem_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_1 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/mb_subsystem/mb_subsystem_ooc.xdc
