# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Digitizer_ladeni/Digitizer.cache/wt [current_project]
set_property parent.project_path C:/Digitizer_ladeni/Digitizer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_repo_paths c:/Digitizer_ladeni/hdl-2017_r1 [current_project]
set_property ip_output_repo c:/Digitizer_ladeni/Digitizer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set src_rc [catch { 
  puts "source C:/Digitizer_ladeni/Digitizer.srcs/presyn.tcl"
  source C:/Digitizer_ladeni/Digitizer.srcs/presyn.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script C:/Digitizer_ladeni/Digitizer.srcs/presyn.tcl failed"
  return -code error
}
add_files C:/Users/svobi/OneDrive/VUT/ING/DP/sinsamples.coe
add_files C:/Users/svobi/OneDrive/VUT/ING/DP/sinsamples_v2.coe
add_files C:/Digitizer_ladeni/sinsamples.coe
read_vhdl -library xil_defaultlib C:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/hdl/mb_subsystem_wrapper.vhd
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Digitizer_ladeni/Digitizer.srcs/sources_1/new/BRAM_trig.vhd
  C:/Digitizer_ladeni/Digitizer.srcs/sources_1/new/FSM_bram.vhd
  C:/Digitizer_ladeni/Digitizer.srcs/sources_1/new/JESD204_transport_layer.vhd
  C:/Digitizer_ladeni/Digitizer.srcs/sources_1/new/init_gtx_reset.vhd
  C:/Digitizer_ladeni/Digitizer.srcs/sources_1/new/TOP.vhd
}
read_ip -quiet C:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_static_config_0/jesd204_rx_static_config_0.xci

read_ip -quiet C:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/jesd204_phy_0.xci
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/ip_0/jesd204_phy_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/ip_0/jesd204_phy_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/synth/jesd204_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/synth/jesd204_phy_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_phy_0_2/synth/jesd204_phy_0_clocks.xdc]

add_files C:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/mb_subsystem.bd
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/constraints/mb_subsystem_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_intc_0/mb_subsystem_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_rst_mig_7series_0_100M_0/mb_subsystem_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_1ed2_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1ed2_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1ed2_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_2/bd_1ed2_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/ip/ip_3/bd_1ed2_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/bd_0/bd_1ed2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/mb_subsystem_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_0/synth/mb_subsystem_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_timer_0_0/mb_subsystem_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_dma_0/mb_subsystem_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_refclk_0/mb_subsystem_axi_ethernet_0_refclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_refclk_0/mb_subsystem_axi_ethernet_0_refclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_ethernet_0_refclk_0/mb_subsystem_axi_ethernet_0_refclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_12/bd_f2d6_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_21/bd_f2d6_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_27/bd_f2d6_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_36/bd_f2d6_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_42/bd_f2d6_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_46/bd_f2d6_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_53/bd_f2d6_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_54/bd_f2d6_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_55/bd_f2d6_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_56/bd_f2d6_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_57/bd_f2d6_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_58/bd_f2d6_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_47/bd_f2d6_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_48/bd_f2d6_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_49/bd_f2d6_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_50/bd_f2d6_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_51/bd_f2d6_m00bn_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_43/bd_f2d6_sawn_2/bd_f2d6_sawn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_43/bd_f2d6_sawn_2/bd_f2d6_sawn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_43/bd_f2d6_sawn_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_44/bd_f2d6_swn_2/bd_f2d6_swn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_44/bd_f2d6_swn_2/bd_f2d6_swn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_44/bd_f2d6_swn_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_45/bd_f2d6_sbn_2/bd_f2d6_sbn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_45/bd_f2d6_sbn_2/bd_f2d6_sbn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_45/bd_f2d6_sbn_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_37/bd_f2d6_sarn_3/bd_f2d6_sarn_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_37/bd_f2d6_sarn_3/bd_f2d6_sarn_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_37/bd_f2d6_sarn_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_38/bd_f2d6_srn_3/bd_f2d6_srn_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_38/bd_f2d6_srn_3/bd_f2d6_srn_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_38/bd_f2d6_srn_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_28/bd_f2d6_sarn_2/bd_f2d6_sarn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_28/bd_f2d6_sarn_2/bd_f2d6_sarn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_28/bd_f2d6_sarn_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_29/bd_f2d6_srn_2/bd_f2d6_srn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_29/bd_f2d6_srn_2/bd_f2d6_srn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_29/bd_f2d6_srn_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_30/bd_f2d6_sawn_1/bd_f2d6_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_30/bd_f2d6_sawn_1/bd_f2d6_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_30/bd_f2d6_sawn_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_31/bd_f2d6_swn_1/bd_f2d6_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_31/bd_f2d6_swn_1/bd_f2d6_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_31/bd_f2d6_swn_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_32/bd_f2d6_sbn_1/bd_f2d6_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_32/bd_f2d6_sbn_1/bd_f2d6_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_32/bd_f2d6_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_22/bd_f2d6_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_23/bd_f2d6_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_13/bd_f2d6_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_14/bd_f2d6_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_15/bd_f2d6_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_16/bd_f2d6_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_17/bd_f2d6_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_4/bd_f2d6_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_5/bd_f2d6_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_6/bd_f2d6_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_7/bd_f2d6_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_8/bd_f2d6_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_1/bd_f2d6_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_1/bd_f2d6_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_2/bd_f2d6_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_2/bd_f2d6_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_3/bd_f2d6_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_3/bd_f2d6_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_0_1/mb_subsystem_axi_quad_spi_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_0_1/mb_subsystem_axi_quad_spi_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_0_1/mb_subsystem_axi_quad_spi_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_0_1/mb_subsystem_axi_quad_spi_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/mb_subsystem_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_1_0/mb_subsystem_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_1_0/mb_subsystem_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_1_0/mb_subsystem_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_quad_spi_1_0/mb_subsystem_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_1/mb_subsystem_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all C:/Digitizer_ladeni/Digitizer.srcs/sources_1/bd/mb_subsystem/mb_subsystem_ooc.xdc]

read_ip -quiet C:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_0.xci
set_property used_in_implementation false [get_files -all c:/Digitizer_ladeni/Digitizer.srcs/sources_1/ip/jesd204_rx_0_1/jesd204_rx_constr.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Digitizer_ladeni/Digitizer.srcs/constrs_1/new/Genesys2.xdc
set_property used_in_implementation false [get_files C:/Digitizer_ladeni/Digitizer.srcs/constrs_1/new/Genesys2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TOP -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
